export const teams = {
    "Atl": "hawks",
    "Bos": "celtics",
    "Bro": "nets",
    "Cha": "hornets",
    "Chi": "bulls",
    "Cle": "cavaliers",
    "Dal": "mavericks",
    "Den": "nuggets",
    "Det": "pistons",
    "Gol": "warriors",
    "Hou": "rockets",
    "Ind": "pacers",
    "Lac": "clippers",
    "Lal": "lakers",
    "Mem": "grizzlies",
    "Mia": "heat",
    "Mil": "bucks",
    "Min": "timberwolves",
    "Nor": "pelicans",
    "Nyk": "knicks",
    "Okc": "thunder",
    "Orl": "magic",
    "Phi": "sixers",
    "Pho": "suns",
    "Por": "trailblazers",
    "Sac": "kings",
    "San": "spurs",
    "Tor": "raptors", 
    "Uta": "jazz",
    "Was": "wizards"
}

export const stats = {
    "apg" : "Assists",
    "ast_per" : "Assist Percentage",
    "bpg" : "Blocks",
    "drtg": "Defensive Rating",
    "efg_per" : "Effective Field Goal %",
    "ft_per": "Free Throw Percentage",
    "fta" : "Free Throws Attempted",
    "gp" : "Games Played",
    "mpg" : "Minutes Per Game",
    "ortg" : "Offensive Rating",
    "ppg" : "Points",
    "rpg" : "Rebounds",
    "spg" : "Steals",
    "three_pa": "Threes Attempted",
    "three_per" : "Three Point %",
    "topg" : "Turnovers",
    "tor": "Turnover Rate",
    "trb_per" : "Total Rebound Percentage",
    "ts_per": "True Shooting %",
    "two_pa": "Two Points Attempted",
    "two_per" : "Two Points %",
    "usg_per" : "Usage Percentage"
}